# Validates a feature branch is deployable prior to merging into main
# Carries out the following in parallel:
# 1. Run all Jest tests
# 2. Create a scratch org WITHOUT package namespace, deploy and run all apex tests
# 3. Create scratch orgs WITH package namespace, deploy and run all apex tests

name: Validate Branch is Deployable

# Run only on demand or on PRs to main
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  JWT_SIGNING_KEY:  ${{ secrets.JWT_SIGNING_KEY }}
  CONSUMER_KEY:     ${{ secrets.CONSUMER_KEY }}
  DEV_HUB_USERNAME: ${{ secrets.DEV_HUB_USERNAME }}

jobs:

  deploy-and-test-without-namespace:
    name: Deploy to fresh scratch org
    runs-on: ubuntu-latest
    container: salesforce/salesforcedx:latest-full
    steps:

    # Checkout branch so we have source code in working directory
    - name: 'Checkout source code'
      uses: actions/checkout@v2

    # Authenticate DevHub
    - name: Output key
      run: |
        echo "${{ secrets.JWT_SIGNING_KEY }}" > server.key
        ls
      shell: bash

    # Authenticate DevHub
    - name: Show files
      run: |
        ls
      shell: bash

    # Authenticate DevHub
    - name: Authenticate and set default DevHub
      run: |
        sfdx force:auth:jwt:grant --clientid $CONSUMER_KEY --jwtkeyfile server.key --username $DEV_HUB_USERNAME --setdefaultdevhubusername -a devhub
      shell: bash

    - name: Create scratch org
      run: |
        sfdx force:org:create -f config/project-scratch-def.json --setdefaultusername -d 1

    - name: Push source
      run: |
        sfdx force:source:push

    - name: Delete scratch org
      run: |
        sfdx force:org:delete -p
